##############################################################################
#                            Producer Collections                            #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#      https://metamanager.wiki/en/latest/defaults/movie/producer.html       #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "160"

collections:
  Producers Collections:
    template:
      - name: separator
        separator: producer
        key_name: Producers
        translation_key: separator

dynamic_collections:
  Top Producers:
    type: producer
    title_format: <<key_name>> (Producer)
    data:
      depth: 5
      limit: 25
    template:
      - tmdb_person
      - smart_filter
      - shared
    template_variables:
      tmdb_person:
        default: <<value>>
      tmdb_person_offset:
        default: 0
      search_term:
        default: producer
      search_value:
        default: tmdb
      translation_key:
        default: producer
      style:
        default: bw
      dynamic:
        default: true
