##############################################################################
#                         AniList Charts Collections                         #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#       https://metamanager.wiki/en/latest/defaults/chart/anilist.html       #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "020"
    image: chart/<<mapping_name_encoded>>

templates:
  anilist:
    default:
      limit: 100
      limit_<<key>>: <<limit>>
      chart: <<key>>
    anilist_<<chart>>: <<limit_<<key>>>>

  season:
    default:
      limit: 100
      limit_trending: <<limit>>
    anilist_search:
      season: current
      year:
      sort_by: popular
      limit: <<limit_trending>>

collections:
  AniList Popular:
    variables:
      key: popular
    template:
      - name: anilist
      - name: shared
        translation_key: anilist_popular
      - name: arr
      - name: custom

  AniList Top Rated:
    variables:
      key: top
    template:
      - name: anilist
        chart: top_rated
      - name: shared
        translation_key: anilist_top_rated
      - name: arr
      - name: custom

  AniList Trending:
    variables:
      key: trending
    template:
      - name: anilist
      - name: shared
        translation_key: anilist_trending
      - name: arr
      - name: custom

  AniList Season:
    variables:
      key: season
    template:
      - name: season
      - name: shared
        translation_key: anilist_season
      - name: arr
      - name: custom
