##############################################################################
#                       FlixPatrol Charts Collections                        #
#           Created by Yozora, Bullmoose20, anon_fawkes, & Sohjiro           #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#     https://metamanager.wiki/en/latest/defaults/chart/flixpatrol.html      #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "020"
    pre: "_#"

templates:
  flixpatrol:
    default:
      location: world
      location_<<key>>: <<location>>
      time_window: last_week
      time_window_<<key>>: <<time_window>>
      limit: 10
      limit_<<key>>: <<limit>>
    conditionals:
      actual_location:
        default: <<location_<<key>>>>
        conditions:
          - key: apple
            value: world
    limit: <<limit>>
    flixpatrol_top:
      platform: <<platform>>
      location: <<actual_location>>
      time_window: <<time_window_<<key>>>>
      limit: <<limit_<<key>>>>

dynamic_collections:
  FlixPatrol:
    type: custom
    data:
      netflix: Netflix
      disney: Disney+
      hbo: HBO
      hulu: Hulu
      paramount: Paramount+
      prime: Prime Video
      apple: Apple TV+
    title_format: <<key_name>> Top <<limit>>
    template:
      - flixpatrol
      - shared
      - arr
      - custom
    template_variables:
      limit:
        default: 10
      platform:
        default: <<key>>
        paramount: paramount_plus
        prime: amazon_prime
        apple: apple_tv
      image:
        default: chart/<<key>>_top
      translation_key:
        default: flixpatrol
      dynamic:
        default: true
