##############################################################################
#                       MyAnimeList Charts Collections                       #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#     https://metamanager.wiki/en/latest/defaults/chart/myanimelist.html     #
##############################################################################

external_templates:
  pmm: templates
  template_variables:
    collection_section: "020"
    image: chart/<<mapping_name_encoded>>

templates:
  mal:
    default:
      limit: 100
      limit_<<key>>: <<limit>>
      chart: <<key>>
    mal_<<chart>>: <<limit_<<key>>>>

  season:
    default:
      limit: 100
      limit_season: <<limit>>
    mal_season:
      season: current
      sort_by: score
      limit: <<limit_season>>

collections:
  MyAnimeList Popular:
    variables:
      key: popular
    template:
      - name: mal
      - name: shared
        translation_key: mal_popular
      - name: arr
      - name: custom

  MyAnimeList Favorited:
    variables:
      key: favorited
    template:
      - name: mal
        chart: favorite
      - name: shared
        translation_key: mal_favorited
      - name: arr
      - name: custom

  MyAnimeList Top Rated:
    variables:
      key: top
    template:
      - name: mal
        chart: all
      - name: shared
        translation_key: mal_top
      - name: arr
      - name: custom

  MyAnimeList Top Airing:
    variables:
      key: airing
    template:
      - name: mal
      - name: shared
        translation_key: mal_airing
      - name: arr
      - name: custom

  MyAnimeList Season:
    variables:
      key: season
    template:
      - name: season
      - name: shared
        translation_key: mal_season
      - name: arr
      - name: custom
